# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = NumberCounter
DESTDIR = ../Bin
QT += core widgets
CONFIG += release
CONFIG += c++11
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += ./tmp/
OBJECTS_DIR += release
UI_DIR += ./tmp/
RCC_DIR += ./tmp/
include(NumberCounter.pri)
win32:RC_FILE = NumberCounter.rc
